version: "3.9"
services:
    app:
        container_name: test_mongo_server
        build: .
        ports:
            - 3000:8080
        links:
            - mongodb


    mongodb:
        container_name: test_mongodb
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: nafiul1916
            MONGO_INITDB_ROOT_PASSWORD: quddus1916
            

        ports:
            - 27017:27017   


        